import { GradeChangeRecord, LogItem } from "./model";

export const DUMMY_RECORDS: GradeChangeRecord[] = [
  {
    id: 1,
    grade_customer_id: "C1",
    grade_customer_name: "Customer 1 ",
    grade_gedu_legal_name: "Customer 1001",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "",
    status: "INITIAL",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 2,
    grade_customer_id: "C2",
    grade_customer_name: "Customer 2",
    grade_gedu_legal_name: "Customer 1002",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "A",
    status: "PENDING_REVIEW",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 3,
    grade_customer_id: "C3",
    grade_customer_name: "Customer 3",
    grade_gedu_legal_name: "Customer 1003",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: undefined,
    status: "PENDING_APPROVAL",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 4,
    grade_customer_id: "C4",
    grade_customer_name: "Customer 4.1",
    grade_gedu_legal_name: "Customer 1004",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "B",
    status: "APPROVED",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 5,
    grade_customer_id: "C5",
    grade_customer_name: "Customer 5",
    grade_gedu_legal_name: "Customer 1005",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "C",
    status: "ASD",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },

  {
    id: 6,
    grade_customer_id: "C6",
    grade_customer_name: "Customer 6",
    grade_gedu_legal_name: "Customer 1006",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "",
    status: "INITIAL",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 7,
    grade_customer_id: "C7",
    grade_customer_name: "Customer 7",
    grade_gedu_legal_name: "Customer 1007",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "A",
    status: "PENDING_REVIEW",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 8,
    grade_customer_id: "C8",
    grade_customer_name: "Customer 8",
    grade_gedu_legal_name: "Customer 1008",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: undefined,
    status: "PENDING_APPROVAL",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 9,
    grade_customer_id: "C9",
    grade_customer_name: "Customer 9",
    grade_gedu_legal_name: "Customer 1009",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "B",
    status: "APPROVED",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 10,
    grade_customer_id: "C10",
    grade_customer_name: "Customer 10",
    grade_gedu_legal_name: "Customer 1010",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "C",
    status: "PENDING_REVIEW",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },

  {
    id: 11,
    grade_customer_id: "C11",
    grade_customer_name: "Customer 11",
    grade_gedu_legal_name: "Customer 1011",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "",
    status: "INITIAL",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 12,
    grade_customer_id: "C12",
    grade_customer_name: "Customer 12",
    grade_gedu_legal_name: "Customer 1012",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "A",
    status: "PENDING_REVIEW",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 13,
    grade_customer_id: "C13",
    grade_customer_name: "Customer 13",
    grade_gedu_legal_name: "Customer 1013",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: undefined,
    status: "PENDING_APPROVAL",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 14,
    grade_customer_id: "C14",
    grade_customer_name: "Customer 14",
    grade_gedu_legal_name: "Customer 1014",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "B",
    status: "APPROVED",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
  {
    id: 15,
    grade_customer_id: "C15",
    grade_customer_name: "Customer 15",
    grade_gedu_legal_name: "Customer 1015",
    grade_default_date: "6/6/2025",
    grade_grp_default_reason_desc: "C",
    status: "PENDING_REVIEW",
    grade_region: "EU",
    grade_method: "Method 1",
    grade_resolution_date: "6/6/2025",
    field1: "FIELD_VALUE",
    field2: "FIELD_VALUE",
    field3: "FIELD_VALUE",
    field4: "FIELD_VALUE",
    field5: "FIELD_VALUE",
  },
];

export const DATA_LOGITEMS: LogItem[] = [
  {
    change_record_id: 1,
    user_role: "VIEWER",
    action: "SUBMIT_FOR_REVIEW",
    comments: "Enough infomation for review",
    creation_date: "2025-06-24T14:58:33.815517",
  },
  {
    change_record_id: 2,
    user_role: "REVIEWER",
    action: "MODIFY",
    comments: "",
    creation_date: "2025-06-24T14:58:33.815517",
    changes: [
      {
        field_name: "Default Date",
        old_value: "2025-04-24T14:58:33.815517",
        new_value: "2025-07-24T14:58:33.815517",
      },
      {
        field_name: "Default Reason",
        old_value: "3 consecutive repayment default",
        new_value: "Tenure Restructured",
      },
    ],
  },
  {
    change_record_id: 3,
    user_role: "REVIEWER",
    action: "SUBMIT_FOR_APPROVAL",
    comments: "Based on new findings, ready for approval",
    creation_date: "2025-06-24T14:58:33.815517",
  },
  {
    change_record_id: 4,
    user_role: "APPROVER",
    action: "APPROVE",
    comments: "",
    creation_date: "2025-06-24T14:58:33.815517",
  },
  {
    change_record_id: 1,
    user_role: "VIEWER",
    action: "SUBMIT_FOR_REVIEW",
    comments: "Enough infomation for review",
    creation_date: "2025-06-24T14:58:33.815517",
  },
  {
    change_record_id: 2,
    user_role: "REVIEWER",
    action: "MODIFY",
    comments: "",
    creation_date: "2025-06-24T14:58:33.815517",
    changes: [
      {
        field_name: "Default Date",
        old_value: "2025-04-24T14:58:33.815517",
        new_value: "2025-07-24T14:58:33.815517",
      },
      {
        field_name: "Default Reason",
        old_value: "3 consecutive repayment default",
        new_value: "Tenure Restructured",
      },
    ],
  },
  {
    change_record_id: 3,
    user_role: "REVIEWER",
    action: "SUBMIT_FOR_APPROVAL",
    comments: "Based on new findings, ready for approval",
    creation_date: "2025-06-24T14:58:33.815517",
  },
  {
    change_record_id: 4,
    user_role: "APPROVER",
    action: "APPROVE",
    comments: "",
    creation_date: "2025-06-24T14:58:33.815517",
  },
];
//Approved based on recent changes
