import { MdlUser } from "@/types/mdl-user";

export const DEFAULT_MDL_USER: MdlUser[] = [
  {
    id: 1,
    name: "Alex Walter",
    role: "REVIEWER",
    ad_user_id: 10001,
    region: "Asia-Pacific",
    site: "HongKong",
    image_url: "female.png",
    creation_date: new Date().toISOString(),
    creation_user: "admin",
    last_modification_date: new Date().toISOString(),
    last_modification_user: "admin",
  },
  {
    id: 2,
    name: "Mark Spencer",
    role: "APPROVER",
    ad_user_id: 10002,
    region: "Asia-Pacific",
    site: "HongKong",
    image_url: "male.png",
    creation_date: new Date().toISOString(),
    creation_user: "admin",
    last_modification_date: new Date().toISOString(),
    last_modification_user: "admin",
  },
  {
    id: 3,
    name: "Tom Pearson",
    role: "APPROVER",
    ad_user_id: 10002,
    region: "Asia-Pacific",
    site: "HongKong",
    creation_date: new Date().toISOString(),
    creation_user: "admin",
    last_modification_date: new Date().toISOString(),
    last_modification_user: "admin",
  },

  {
    id: 4,
    name: "Alex Walter",
    role: "REVIEWER",
    ad_user_id: 10001,
    region: "Asia-Pacific",
    site: "HongKong",
    image_url: undefined,
    creation_date: new Date().toISOString(),
    creation_user: "admin",
    last_modification_date: new Date().toISOString(),
    last_modification_user: "admin",
  },
  {
    id: 5,
    name: "Mark Spencer",
    role: "APPROVER",
    ad_user_id: 10002,
    region: "Asia-Pacific",
    site: "HongKong",
    image_url: "male.png",
    creation_date: new Date().toISOString(),
    creation_user: "admin",
    last_modification_date: new Date().toISOString(),
    last_modification_user: "admin",
  },
  {
    id: 6,
    name: "Tom Pearson",
    role: "APPROVER",
    ad_user_id: 10002,
    region: "Asia-Pacific",
    site: "HongKong",
    image_url: "void.png",
    creation_date: new Date().toISOString(),
    creation_user: "admin",
    last_modification_date: new Date().toISOString(),
    last_modification_user: "admin",
  },
];
